# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fd421150cde5e94daa5d85cc77123c4"
name = "hbv2"
application_url = "https://ea17-103-157-37-46.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
